# Must be kept in sync with vacuum.py
refresh:
  target:
    entity:
      integration: deebot
      domain: vacuum
  fields:
    part:
      required: true
      advanced: false
      example: "status"
      default: "status"
      selector:
        select:
          translation_key: "refresh_part"
          options:
            - "battery"
            - "clean_logs"
            - "error"
            - "fan_speed"
            - "life_spans"
            - "map"
            - "rooms"
            - "stats"
            - "status"
            - "water"
