default_config:

logger:
  default: info
  logs:
    homeassistant.components.vacuum: debug
    custom_components.deebot: debug
    deebot_client: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
