name: PR artifacts

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    permissions:
      # Required to upload/save artifact, otherwise you'll get
      # "Error: Resource not accessible by integration"
      contents: write
      # Required to post comment, otherwise you'll get
      # "Error: Resource not accessible by integration"
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4

      - name: 📦 Create zip file for the integration
        run: |
          cd "${{ github.workspace }}/custom_components/deebot"
          zip deebot.zip -r ./
      - name: 📤 Create comment with the artifiactory
        uses: gavv/pull-request-artifacts@v2
        with:
          # Commit hash that triggered PR
          commit: ${{ github.event.pull_request.head.sha }}

          # Token for current repo (used to post PR comment)
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          artifacts-branch: artifacts

          # Whitespace-separated list of files to upload
          artifacts: |
            deebot.zip
